### ISSUE TITLE
Resolves done wrong

### ISSUE THREAD

**Issue by pepzwee** [pepzwee/node-steam-market-crawler#4]
Note to self: Stop being stupid and RTFM.

http://stackoverflow.com/questions/35805603/are-nested-promises-normal-in-node-js
https://blog.domenic.me/youre-missing-the-point-of-promises/
http://www.datchley.name/promise-patterns-anti-patterns/

**Comment by ConnorMcF** [comment]
nice one

**Comment by pepzwee** [comment]
@ConnorMcF please cure me of this stupidity, oh wait.. you had a file with 1,4k lines of code 😆 🔥

**Comment by ConnorMcF** [comment]
cheers
