### ISSUE TITLE
Todos?

### ISSUE THREAD

**Issue by w0bbes** [pepzwee/node-steam-market-crawler#7]
Hey man, let me know if you are looking to add some features.

**Comment by pepzwee** [comment]
`https://steamcommunity.com/market/listings/{appid}/{market_hash_name}/render/?query=&start={start}&count={count}`

This endpoint needs to be added Soon™

**Comment by w0bbes** [comment]
Allright, ill see if I can help out tomorrow.

Also, I'm looking to add a listing of all the items from an appid. Is that something you find usefull aswell?

**Comment by pepzwee** [comment]
Yeah, make a PR if you feel like adding them

**Comment by w0bbes** [comment]
Will do man. Thanks

**Comment by w0bbes** [comment]
Still working on stuff. But ill let you know when it's done, sorry. Very busy

**Comment by pepzwee** [comment]
I already implemented the endpoint, you can make suggestions on how to make it better if you wish to do so.
